#!/bin/zsh

# read environments
. ./.environment

# prepare install directory
echo -n "Cleanup $HOME_EMACS_INSTALL_ROOT ... "
. ./utils/cleanup
mkdir -p "$HOME_EMACS_INSTALL_ROOT" || exit 1

# make site-lisp directory
echo -n "Create site-lisp director $HOME_EMACS_SITE_LISP ... "
mkdir -p "$HOME_EMACS_SITE_LISP" || exit 1
echo "OK"

# org dir
echo -n "Create $HOME_EMACS_ORG_DiR .. "
mkdir -p "$HOME_EMACS_ORG_DIR" || exit 1
touch "$HOME_EMACS_ORG_DEFAULT_FILE" || exit 1

# make start script
echo -n "Create start script ... "
sed "s,@HOME_EMACS_SITE_LISP@,$HOME_EMACS_SITE_LISP,g" "$HOME_EMACS_TEMPLATE_DIR/home-emacs-daemon.in" > "$HOME_EMACS_INSTALL_ROOT/home-emacs-daemon" || exit 1
chmod +x "$HOME_EMACS_INSTALL_ROOT/home-emacs-daemon" || exit 1
echo "OK"

# install files
. ./utils/copy-modules

# install emacs packages and exit
. ./utils/install-packages

# install custom packages

. ./utils/distel-install.sh

