#!/bin/zsh

. ./.environment

template_module() {
    module=`basename $1 .el.in`
    echo -n "Create $2/$module.el ... "
    sed  "s,@HOME_EMACS_SITE_LISP@,$HOME_EMACS_SITE_LISP,g; s,@HOME_EMACS_ORG_DEFAULT_FILE@,$HOME_EMACS_ORG_DEFAULT_FILE,g" "$1" > "$2/$module.el" || exit 1
echo "OK"    
}

template_modules() {
    echo "Template modules processing"
    echo "Site lisp: $2"
    for file in "$1"/*.el.in; do
	template_module "$file" "$HOME_EMACS_SITE_LISP" || exit 1
    done
}

template_modules "$HOME_EMACS_TEMPLATE_DIR" "$HOME_EMACS_SITE_LISP" || exit 1

echo "Copy *.el files ... "
for file in "$HOME_EMACS_FILES_DIR/"*.el; do
    destination="$HOME_EMACS_SITE_LISP/"
    echo "Copy $file -> $destination"
    cp "$file" "$destination" || exit 1
done
echo "OK"

