#!/bin/zsh

. ./.environment

echo -n "Cleanup packages dir ... "
rm -rf "$HOME_EMACS_SITE_LISP"/packages
echo "ok"

echo "Install pakcages $HOME_EMACS_SITE_LISP/home-install-packages.el ... "
emacs -l "$HOME_EMACS_SITE_LISP/home-install-packages.el"
echo "OK"

